#!/usr/bin/env bash
#
# tap-bump-script.sh — bump the Murmur cask in roshanshah11/homebrew-murmur.
#
# Invoked from the main repo's release.yml after the DMG has been built,
# signed, notarized, and uploaded to a GitHub Release.
#
# Required environment:
#   VERSION       — semver, no leading "v"   (e.g. "1.0.3")
#   DMG_SHA256    — 64-char lowercase hex SHA-256 of Murmur-<VERSION>.dmg
#   GITHUB_TOKEN  — PAT or workflow token with `repo` scope on homebrew-murmur
#
# Optional:
#   RELEASE_NOTES — markdown body to include in the PR description
#   TAP_REPO      — defaults to roshanshah11/homebrew-murmur
#   GIT_USER_NAME — defaults to "murmur-release-bot"
#   GIT_USER_EMAIL — defaults to "release-bot@murmur.app"
#
# Exit codes:
#   0  PR opened (or already exists for this version)
#   1  bad input / missing env
#   2  git / gh failure

set -euo pipefail

: "${VERSION:?VERSION is required (semver, no leading v)}"
: "${DMG_SHA256:?DMG_SHA256 is required}"
: "${GITHUB_TOKEN:?GITHUB_TOKEN is required}"

TAP_REPO="${TAP_REPO:-roshanshah11/homebrew-murmur}"
RELEASE_NOTES="${RELEASE_NOTES:-Automated bump. See main repo release for details.}"
GIT_USER_NAME="${GIT_USER_NAME:-murmur-release-bot}"
GIT_USER_EMAIL="${GIT_USER_EMAIL:-release-bot@murmur.app}"

# --- sanity ----------------------------------------------------------------

if ! [[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[A-Za-z0-9.-]+)?$ ]]; then
  echo "::error::VERSION '$VERSION' is not a valid semver" >&2
  exit 1
fi

if ! [[ "$DMG_SHA256" =~ ^[a-f0-9]{64}$ ]]; then
  echo "::error::DMG_SHA256 must be 64 lowercase hex chars" >&2
  exit 1
fi

command -v gh >/dev/null || { echo "::error::gh CLI not on PATH"; exit 2; }
gh auth status >/dev/null 2>&1 || gh auth login --with-token <<<"$GITHUB_TOKEN"

# --- workspace -------------------------------------------------------------

WORKDIR="$(mktemp -d -t murmur-tap-bump.XXXXXX)"
trap 'rm -rf "$WORKDIR"' EXIT

cd "$WORKDIR"
gh repo clone "$TAP_REPO" tap -- --depth=1
cd tap

git config user.name "$GIT_USER_NAME"
git config user.email "$GIT_USER_EMAIL"

BRANCH="bump/v${VERSION}"
# Idempotent: if PR already merged or branch exists, we still want a clean state.
git checkout -B "$BRANCH" origin/main

CASK="Casks/murmur.rb"
[[ -f "$CASK" ]] || { echo "::error::$CASK not found in $TAP_REPO"; exit 2; }

# --- token substitution ----------------------------------------------------

# We replace the inner quoted-string tokens only — keeps the Ruby file parseable
# before AND after substitution. macOS sed needs -i '' (BSD); GNU sed wants -i.
# The release runner is ubuntu-latest → GNU sed; if you ever run this locally on
# macOS, set SED_INPLACE='-i ""' before invoking.
SED_INPLACE="${SED_INPLACE:--i}"

# shellcheck disable=SC2086
sed $SED_INPLACE \
  -e "s|:auto_bump_version:|${VERSION}|g" \
  -e "s|:auto_bump_sha256:|${DMG_SHA256}|g" \
  "$CASK"

# Verify substitution actually happened (catches a previously-bumped cask).
if grep -q ":auto_bump_" "$CASK"; then
  echo "::error::token substitution failed — :auto_bump_* still present in $CASK" >&2
  exit 2
fi

# --- commit + push ---------------------------------------------------------

if git diff --quiet; then
  echo "::notice::no changes — cask already at v${VERSION}, nothing to do"
  exit 0
fi

git add "$CASK"
git commit -m "chore: bump Murmur to v${VERSION}

DMG SHA-256: ${DMG_SHA256}
"

git push --force-with-lease origin "$BRANCH"

# --- open PR (or update existing) ------------------------------------------

PR_TITLE="chore: bump Murmur to v${VERSION}"
PR_BODY="$(cat <<EOF
Automated bump from the main repo release pipeline.

- **Version:** \`${VERSION}\`
- **DMG SHA-256:** \`${DMG_SHA256}\`
- **Release notes:** see https://github.com/roshanshah11/murmur/releases/tag/v${VERSION}

---

${RELEASE_NOTES}

> Generated by \`tap-bump-script.sh\`. Do not edit \`Casks/murmur.rb\` by hand —
> fix the bump pipeline in the main repo instead.
EOF
)"

if gh pr view "$BRANCH" --repo "$TAP_REPO" >/dev/null 2>&1; then
  gh pr edit "$BRANCH" --repo "$TAP_REPO" --title "$PR_TITLE" --body "$PR_BODY"
  echo "::notice::updated existing PR for $BRANCH"
else
  gh pr create \
    --repo "$TAP_REPO" \
    --base main \
    --head "$BRANCH" \
    --title "$PR_TITLE" \
    --body "$PR_BODY"
fi

echo "::notice::tap bump PR ready for $TAP_REPO @ $BRANCH"
